api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Domain/PrayerTime'
            - '%kernel.project_dir%/src/Domain/QiblaDirection'
            - '%kernel.project_dir%/src/Domain/User'