# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Domain\QiblaDirection\Repository\QiblaDirectionRepository:
        public: true
        arguments:
            $registry: '@doctrine'

    App\Domain\QiblaDirection\Service\QiblaDirectionService:
        public: true
        arguments:
            $qiblaDirectionRepository: '@App\Domain\QiblaDirection\Repository\QiblaDirectionRepository'

    App\Domain\User\Repository\UserRepository:
        arguments:
            $registry: '@doctrine'

    App\Domain\PrayerTime\Repository\PrayerTimeRepository:
        arguments:
            $registry: '@doctrine'

    App\Domain\User\Service\UserService:
        public: true

    App\Infrastructure\Security\TokenService:
        public: true

    App\Infrastructure\Security\PasswordEncoder:
        public: true

    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface:
        alias: lexik_jwt_authentication.jwt_manager

    App\Infrastructure\API\Controller\UserController:
        autowire: true

    App\Infrastructure\API\Controller\PrayerTimeController:

    App\Infrastructure\API\Controller\QiblaDirectionController:
      arguments:
        $qiblaDirectionService: '@App\Domain\QiblaDirection\Service\QiblaDirectionService'